### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Spinwing** [ndphillips/FFTrees#10]
Hello Nathaniel

I'm a newbie in R so bear with me.

I'm getting this error but I don't really get it (hence probably not a bug).

I'm trying to use FFTrees with the Kaggle Titanic dataset. Attached the test and train datasets, after features engineering as per Stephens' tutorial.

```
fft <- FFTrees(formula=Survived~Pclass + Sex + Age + SibSp + Parch + 
                   Fare + Embarked + Title + FamilySize + FamilyID2, 
                 data=train, train.p=0.75, max.levels = 5)

> predict(fft, test)
Error in if (hr.v[i] >= hr.v.n[length(hr.v.n)] & far.v[i] >= far.v.n[length(far.v.n)]) { : 
  missing value where TRUE/FALSE needed
```

I thought, well the Survived in the test is NA, therefore let's put it to 0.

```
test$Survived <- as.integer(1)
predict(fft, test)
Error in if (hr.v[i] >= hr.v.n[length(hr.v.n)] & far.v[i] >= far.v.n[length(far.v.n)]) { : 
  missing value where TRUE/FALSE needed
```

Error does not help me much in trying to figure the issue. The two datasets are identical in structure, what am I missing?

Thanks 
[Titanic.Kaggle.zip](https://github.com/ndphillips/FFTrees/files/438018/Titanic.Kaggle.zip)

**Comment by ndphillips** [comment]
@Spinwing Thanks for the good example code and the dataset!

The problem is that your test dataset has NA values for the criterion `Survived`. The `FFTrees()` function requires that you have complete (no NA) logical vector for the criterion variable.

I altered your code by adding random 0s and 1s to the Survived column in your test dataset.

```
tit.train <- read.table("~/Downloads/Titanic.Kaggle/titanic.train.csv", sep = ",", header = T)
tit.test <- read.table("~/Downloads/Titanic.Kaggle/titanic.test.csv", sep = ",", header = T)

library(FFTrees)

fft <- FFTrees(formula = Survived ~ Pclass + Sex + Age + SibSp + Parch + 
                 Fare + Embarked + Title + FamilySize + FamilyID2, 
               data = tit.train,
               max.levels = 5)

# Here are the trees in the fft object. There are 10 of them
fft$tree.stats

# Add random criterion values for the test dataset (just so we can make predictions)
tit.test$Survived <- sample(c(0, 1), size = nrow(tit.test), replace = T)

tit.fft.pred <- predict(fft, data = tit.test)

# Here are the FFTrees decisions for each of the cases for each of the 10 trees
head(tit.fft.pred $decision)

# Here are the predictions for tree 6 (the 'best' tree in the training dataset)
tit.fft.pred$decision[,6]

# The tree statistics in the prediction object are meaningless as they are applied to random data
tit.fft.pred$tree.stats
```
Thanks for the example, it also reminds me that I need to add nicer printing options to the `predict.FFTrees()` function.

If you need something different let me know!

**Comment by Spinwing** [comment]
Thank for the prompt reply. 

I came to the same conclusion, and I did (see above) set the value of Survived to 1 before running the predict. I got the error. As I'm kind of stubborn ;)

```
titanic.test$Survived <- as.integer(0)
> tit.fft.pred <- predict(fft, data = titanic.test)
Error in if (hr.v[i] >= hr.v.n[length(hr.v.n)] & far.v[i] >= far.v.n[length(far.v.n)]) { : 
        missing value where TRUE/FALSE needed
    
titanic.test$Survived <- sample(c(0, 1), size = nrow(titanic.test), replace = T)
> tit.fft.pred <- predict(fft, data = titanic.test)
```

Why if I set all to Survived=0 it does not work, but if I use your command(which simply randomly assigns 0 or 1) it does work?

BTW compliments for the nice work, your library is easy to use even for a newbie, and the output is very useful and self explaining.

Thanks

**Comment by ndphillips** [comment]
Yes there will be a problem if you only include 0s or 1s - the criterion must be a mixture of both 0s and 1s otherwise some of the accuracy calculations (HR and FAR) return NA values.

I probably should include a warning or correction factor that works around this...but in most real datasets, there should always be a mixture of some positive and some negative criterion values in both training and test datasets.

I'm glad you're enjoying the package otherwise!

**Comment by Spinwing** [comment]
Ah I see, ok, maybe worth documenting for the noobs like me ;)

Thanks!
