### ISSUE TITLE
Incomplete names and overlapping boxes

### ISSUE THREAD

**Issue by gorkang** [ndphillips/FFTrees#13]
In some of the trees the boxes overlap with other stuff (see red shaded area in reproducible example attached).

Also, there is a way to change the number of characters shown for the variable names? In some cases , this makes impossible to see which of the variables has been selected (e.g. BIS_Nonpla could be BIS_Nonplanning or BIS_Nonplanning_SelfControl).

Thanks!

[BUG FFTrees.zip](https://github.com/ndphillips/FFTrees/files/542525/BUG.FFTrees.zip)

**Comment by ndphillips** [comment]
Thanks for catching the bug and showing the examples!

Indeed, the overlapping labels was an issue in cases (such as yours) where no data are classified in a level. This has been fixed in FFTrees 1.1.9 (up on github, submitted to CRAN...).

With regards to the variable names...I'll have to think about this some more. The ideal solution would be to automatically resize the text based on how many characters it contains. I'll try to figure out how to do this...
