### ISSUE TITLE
Question: Extracting information for each terminal node

### ISSUE THREAD

**Issue by andreashandel** [ndphillips/FFTrees#37]
Hi,
I'd like to be able to extract the numbers (hits and misses) for each terminal node of a tree. I know it can be done somehow since those numbers and icons are shown in the plot. But I just can't figure out how to pull them out of the list that FFTrees() returns, despite reading though all the vignettes and the manual. Any help on how to do that would be appreciated. 

Also, I noticed that sometimes, for some trees, one of the final nodes has many more wrong than right predictions and performance should be better if one predicted simply the opposite. E.g. in your mushroom vignette the bottom left terminal node only mis-predicts, if those were all predicted as poisonous wouldn't that lead to a better tree/model? I see the same for some of my data and I"m trying to understand why this is happening.

Overall great package! I just discovered it recently and I'm fairly sure I'll use it a fair bit for my work!

**Comment by ndphillips** [comment]
Hi @andreashandel ,

You can get the numbers from the terminal nodes in the `$level.stats` output. 

![image](https://user-images.githubusercontent.com/8480980/39813175-b1bea7de-538f-11e8-8148-c07cd266148b.png)

The statistics are cumulative, so if you want the marginal numbers at each node, you'll have to subtract the cumulative number from each node from the value at the previous node.

With regards to final nodes having more wrong that right predictions, this is indeed a common result! The reason for it is that, by default, the trees maximize balanced accuracy, the average of sensitivity and specificity. If you have very imbalanced classes, e.g.; A = 90% vs B = 10%, then the tree has to 'work' very hard to classify sufficient numbers of the rare class. In some cases, the only way to do this might be to incorrectly classify many of the A class in order to get some correct decisions for the rare B class. This can mean that some nodes will produce more incorrect decisions than correct decisions.

If you don't like this feature, you can always play around by creating your own trees with `my.tree` where you reverse the decisions of some node. Or, you can force the trees  to maximise overall accuracy with the arguments `goal = 'acc'`, `goal.chase = 'acc'`. If you do this, then you definitely should not see nodes that make more incorrect decisions than correct ones. If you do, let me know so I can take a closer look :)

Hope this helps!
