### ISSUE TITLE
FFTrees removed from CRAN on 2020-07-23

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [ndphillips/FFTrees#47]
FFTrees can be no longer installed from CRAN (https://cran.r-project.org/package=FFTrees)

- maybe you did not notice :)

**Comment by ndphillips** [comment]
Yeah I've been meaning to get on that! Will see if some coffee this morning will help jump start that today...

**Comment by ndphillips** [comment]
Resubmitted 1.5.7 today. Fingers crossed...

**Comment by ajwills72** [comment]
Seem like it's not yet returned to CRAN?

**Comment by fh-nphillips** [comment]
Yep still struggling to solve the issues. Here are the latest suggestions from Gregor Seyer. I f someone has time to help tackle them I would be grateful for the help!

If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

Please write TRUE and FALSE instead of T and F. (Please don't use 'T' or
'F' as vector names.)

You write information messages to the console that cannot be easily
suppressed.
It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.
Instead of print()/cat() rather use message()/warning()  or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console.
(except for print, summary, interactive functions)

Please make sure that you do not change the user's options, par or
working directory. If you really have to do so within functions, please
ensure with an *immediate* call of on.exit() that the settings are reset
when the function is exited. e.g.:
...
oldpar <- par(no.readonly = TRUE)    # code line i
on.exit(par(oldpar))            # code line i + 1
...
par(mfrow=c(2,2))            # somewhere after
...
e.g.: plotFFTrees_function.R, showcues_function.R
If you're not familiar with the function, please check ?on.exit. This
function makes it possible to restore options before exiting a function
even if the function breaks. Therefore it needs to be called immediately
after the option change within a function.


Please always make sure to reset to user's options(), working directory
or par() after you changed it in examples and vignettes and demos.
e.g.:

old <- options(digits = 3)
...
options(old)


Additionally:
Have the issues why your package was archived been fixed?
Please explain this in the submission comments.


Please fix and resubmit.

**Comment by aldinaisabel** [comment]
Nathaniel Phillips

Congratulations for your very interesting package!
I would love to use it! 
Do you know when it will be available again?
The recommendations above are not very explicit for those who don't know the code, I can't help! I'm sorry! 
You sure can do it! 🥇 👍 
I look forward to it! 

Thank you
Aldina

**Comment by ndphillips** [comment]
Back on CRAN as of today! See https://cran.r-project.org/web/packages/FFTrees/index.html
