### ISSUE TITLE
Custom trees created with my.tree do not match specifications

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/FFTrees#60]
I just explored the custom tree(s) created  with `my.tree` in the readme and realized that the last node is incorrect.

The specification:

my.tree = "If sex = 1, predict Disease.
                             If age < 45, predict Healthy.
                             If thal = {fd, normal}, predict Disease. 
                             Otherwise, predict Healthy"

leads to the following definition

[1] "If sex = 1, decide Disease"                                      
[2] "If age < 45, decide Healthy"                                     
[3] "If thal = {fd,normal}, decide Healthy (!Not Disease as expected), otherwise, decide Disease (Not Healthy as expected)

See code below:

```
> library(FFTrees)

   O      
  / \     
 F   O  
    / \   
   F   Trees 1.6.6.9003

Email: Nathaniel.D.Phillips.is@gmail.com
FFTrees.guide() opens the main guide.
> # Create my own fft
> my.fft <- FFTrees(formula = diagnosis ~., 
+                   data = heart.train,
+                   data.test = heart.test, 
+                   decision.labels = c("Healthy", "Disease"),
+                   my.tree = "If sex = 1, predict Disease.
+                              If age < 45, predict Healthy.
+                              If thal = {fd, normal}, predict Disease. 
+                              Otherwise, predict Healthy")
Setting goal = 'wacc'
Setting goal.chase = 'waccc'
Setting cost.outcomes = list(hi = 0, mi = 1, fa = 1, cr = 0)
Fitting other algorithms for comparison (disable with do.comp = FALSE) ...
> 
> my.fft
FFTrees 
- Trees: 1 fast-and-frugal trees predicting diagnosis
- Outcome costs: [hi = 0, mi = 1, fa = 1, cr = 0]

FFT #1: Definition
[1] If sex = 1, decide Disease.
[2] If age < 45, decide Healthy.
[3] If thal = {fd,normal}, decide Healthy, otherwise, decide Disease.

FFT #1: Prediction Accuracy
Prediction Data: N = 153, Pos (+) = 73 (48%) 

|         | True + | True - |
|---------|--------|--------|
|Decide + | hi 70  | fa 45  | 115
|Decide - | mi 3   | cr 35  | 38
|---------|--------|--------|
            73       80       N = 153

acc  = 68.6%  ppv  = 60.9%  npv  = 92.1%
bacc = 69.8%  sens = 95.9%  spec = 43.8%
E(cost) = 0.314

FFT #1: Prediction Speed and Frugality
mcu = 1.59, pci = 0.88
> my.fft$trees$definitions
# A tibble: 1 × 7
   tree nodes classes cues         directions thresholds     exits 
  <int> <int> <chr>   <chr>        <chr>      <chr>          <chr> 
1     1     3 n;n;c   sex;age;thal =;>=;!=    1;45;fd,normal 1;0;.5
> my.fft$trees$inwords
[[1]]
[1] "If sex = 1, decide Disease"                                      
[2] "If age < 45, decide Healthy"                                     
[3] "If thal = {fd,normal}, decide Healthy, otherwise, decide Disease"

```

**Comment by hneth** [comment]
**Update:**  The bug seems to be caused by _always_ reversing cue directions of the final node (as there always is an exit with a FALSE criterion value).  My latest commits may fix this bug by making 2 changes:

1. `fftrees_wordstofftrees()` now ignores anything after "otherwise" (i.e., the 2nd part of the last sentence of a verbal FFT description). This prevents the final cue direction from _always_ being reversed.

2. In the final sentence ("If A, otherwise B"), `fftrees_ffttowords()` now always predicts/decides positive criterion instances (TRUE cases in A) prior to negative criterion instances (FALSE cases in B). This renders additional reversals of cue directions obsolete.

Some initial checks are included in the `FFTrees_mytree.Rmd` vignette, but further checks should be done.

(based on https://github.com/ndphillips/FFTrees/pull/61#discussion_r930491894 )

**Comment by hneth** [comment]
Just verified that my bug fixes from yesterday seem to work without introducing new issues.  (For instance, providing a nonsensical "otherwise" part in the verbal description of the final node has no effects, as the "otherwise" part is ignored.) 

Hence, unless further issues emerge, I'd consider this issue closed.
